# This file contains the window settings and defines constants for the game.

WIDTH, HEIGHT = 800, 640
LOWER_MARGIN, SIDE_MARGIN = 100, 300

ROWS = 16
MAX_COLS = 180

TILE_SIZE = HEIGHT // ROWS
OBSTACLE_SIDE_PADDING = TILE_SIZE * 0.125
TILE_TYPES = 30

TOTAL_LEVELS = 50

TILE_BTN_SPACING_X = 75
TILE_BTN_SPACING_Y = 70
TILE_BTN_OFFSET_X = 50
TILE_BTN_OFFSET_Y = 20

SCROLL_AREA_WIDTH = 200
WORLD_WIDTH = MAX_COLS * TILE_SIZE

OBSTACLE_TILE_COLLISIONS = {
    0: {"x": OBSTACLE_SIDE_PADDING, "y": 5, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": (TILE_SIZE - 5)},   # done
    1: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},     # done
    2: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    3: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    4: {"x": 5 + OBSTACLE_SIDE_PADDING, "y": 0, "w": 15 - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},       # done
    5: {"x": 20 + OBSTACLE_SIDE_PADDING, "y": 0, "w": 15 - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},     # done
    6: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    7: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},   # done
    8: {"x": 15 + OBSTACLE_SIDE_PADDING, "y": 0, "w": (TILE_SIZE - 15) - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},   # done
    9: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": (TILE_SIZE - 10) - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    10: {"x": 18 + OBSTACLE_SIDE_PADDING, "y": 0, "w": (TILE_SIZE - 18) - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    11: {"x": 5 + OBSTACLE_SIDE_PADDING, "y": 0, "w": (TILE_SIZE - 18) - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    12: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    13: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE},    # done
    14: {"x": OBSTACLE_SIDE_PADDING, "y": 0, "w": TILE_SIZE - (OBSTACLE_SIDE_PADDING * 2), "h": TILE_SIZE}    # done
}

FPS = 60

TITLE = "NEA Platformer Game"
LEVEL_EDITOR_TITLE = "NEA Platformer Level Editor"

BLACK = (0, 0, 0)
RED = (173, 26, 26)
BLUE = (16, 22, 185)
CYAN = (7, 255, 255)
TEAL = (26, 195, 170)
GREEN = (11, 130, 14)
LIGHT_GREEN = (0, 255, 0)
YELLOW = (231, 239, 16)
ORANGE = (218, 126, 23)
GRAY = (128, 128, 128)
LIGHT_GRAY = (232, 232, 232)
WHITE = (255, 255, 255)
PURPLE = (89, 17, 153)
PINK = (226, 30, 183)

BG_COLOR = BLACK 
